name: modern_it_homepage
description: ModernIT.space Homepage website.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^1.0.0
  cupertino_icons: ^1.0.1
  get: 3.24.0
  get_it: ^4.0.4
  http: ^0.12.2
  provider: ^4.1.2
  provider_architecture: ^1.1.1+1
  responsive_builder: ^0.3.0

dev_dependencies: null

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/logo-original.png
    - assets/images/office-865091_1920.jpg

  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 400
